### ISSUE TITLE
build issues?

### ISSUE THREAD

**Issue by dorinilut** [jankammerath/iptvx#18]
Hi,

Thanks for your work on this. I look forward to see the final product. I have the following issue on Ubuntu. When trying to do the ./build.sh I get the following errors:

osboxes@osboxes:~/iptvx$ ./build.sh 
src/config.c:32:23: fatal error: libconfig.h: No such file or directory
 #include <libconfig.h>
                       ^
compilation terminated.
src/epg.c:23:23: fatal error: libconfig.h: No such file or directory
 #include <libconfig.h>
                       ^
compilation terminated.
src/main.c:24:23: fatal error: libconfig.h: No such file or directory
 #include <libconfig.h>
                       ^
compilation terminated.
src/util.c:32:23: fatal error: curl/curl.h: No such file or directory
 #include <curl/curl.h>
                       ^
compilation terminated.
src/video.c:19:21: fatal error: vlc/vlc.h: No such file or directory
 #include <vlc/vlc.h>
                     ^
compilation terminated.
src/window.c:25:27: fatal error: SDL/SDL_image.h: No such file or directory
 #include <SDL/SDL_image.h>
                           ^
compilation terminated.

Can you please help?

Many thanks Dorin

**Comment by jankammerath** [comment]
Hi dorinilut,

**Current status of the code**
First of all just a quick info: The current status is "alpha 0.2" and any useful status of the software will not exist until "beta 0.5" which I think I'll finish around March 2017. Anything before "beta 0.5" should be considered "_a bunch of code that may compile on your system_".

**What can be used**
If you're still keen to see the current WIP outcome, you can try to compile it, but you need to check the compiling script (build.sh) to include the correct libraries on your system. I build it on OpenSUSE 42.1 and if you're using a DEB-system like Debian or Ubuntu your development libraries might have different names. You might even be required to change them in the code before compiling.

**Your concrete issue**
The issue you are having is that libvlc, SDLimage, libcurl and libconfig development versions are not present in your system or the compiler cannot find it in your include path. On Debian/Ubuntu the packages end with "-devel" and on SuSE etc. they end with "-dev". So check if you have them.

Just a quick warning: the current status contains config files from development which may cause the program to segfault under some circumstances. It still is a development version and proper functionality cannot be guaranteed at the moment. 

Thank you a lot for your interest in my project! Once the beta is ready for release, there will also be a website under iptvx.org and binary packages (RPM and DEB) are also planned.

**I am closing this ticket as the missing development libraries are your build issue here.**

Cheers, Jan

**Comment by dorinilut** [comment]
Thanks for your quick reply. . I will follow your recommendations. if you
want a stable source for your IPTV testing I have a tvheadend server where
I can provide access. My final intention is to use your software on a
raspberry as a simple TV interface.

I am really looking forward to see the final build and provide testing
using multiple systems.

Dorin

Dorin Ilut
Mobile1: +31647071114
Mobile2: +40727777895
Skype: dorin.ilut.2
