### ISSUE TITLE
Bad configuration file.

### ISSUE THREAD

**Issue by dynamo69** [jankammerath/iptvx#81]
Hello! Excited to see your app and would like to blog about it in the future, however Im getting an error after installation. Im currently using Ubuntu 16.04 and have installed that version DEB file. Here is what Im getting in the terminal...

donald@donald-SX2865:~$ service iptvx start
Failed to start iptvx.service: Unit iptvx.service not found.

donald@donald-SX2865:~$ iptvx
iptvx -- An IPTV player and recorder

You are using version 'iptvx 0.5 beta'
Please file bugs in the issue tracking:
https://github.com/jankammerath/iptvx/issues

Bad configuration file.
/etc/iptvx/iptvx.conf:33 - cannot open include file
Failed to initialise the configuration

**Comment by kiljab** [comment]
Edit your /etc/iptvx/iptvx.conf and point the @include to your local channels.conf file.Mine is at /etc/iptvx/channels.conf. After that the app loads. You may want to edit channels.conf with you m3u8 list of channels.

**Comment by dynamo69** [comment]
This worked thank you!
