### ISSUE TITLE
Is this project still alive? :)

### ISSUE THREAD

**Issue by thomasphansen** [jankammerath/iptvx#82]
Hello,
I've just had a brief look at your project, and became interested on it - do you have plans to keep it going? :)

**Comment by host755** [comment]
imho this is dead at all, no domain active, no link woking, no support, no infos, no...thing ;-)

**Comment by jankammerath** [comment]
I am thinking about potentially rebuilding parts in C++, but I just lack the time to do it and the feedback I received was more that average users want to have that application as an out-of-the-box Desktop software. To be able to provide that, beyond Linux, is a work-load I cannot provide at the moment.

**Comment by thomasphansen** [comment]
Fair enough! :) Personally I don't care for anything beyond Linux - my goal is to have a linux-based multimedia box, running some media center app (plex/kodi) and a nice IPTV app that can handle huge channel lists and still perform (wasn't able to find a decent solution for that yet). Huge here means around 20.000 channels, being updated daily! :)
I'd love to help you on this project (being myself a developer as well), but looks like time is an issue for both of us. Maybe I'll find some time during summer to have a better look at it again. Meanwhile, I can see the installing instructions have been removed from your domain iptvx.org. Would you mind creating them as .md files, together with the master branch? :)
Anyway, thanks for the nice work! :)
