### ISSUE TITLE
daemon issues

### ISSUE THREAD

**Issue by halfagascan** [jankammerath/iptvx#83]
iptvx --daemon
iptvx: unrecognized option '--daemon'
Try `iptvx --help' or `iptvx --usage' for more information.
iptvx --version
iptvx 0.5 beta

sudo systemctl start iptvx
Failed to start iptvx.service: Unit iptvx.service not found.

dpkg --purge iptvx

**Comment by jankammerath** [comment]
Was not implemented as of that version.
