### ISSUE TITLE
It would be nice to have an official Docker image

### ISSUE THREAD

**Issue by alexanderadam** [jankammerath/iptvx#85]
this way it would be very easy to test anything out and also to have a proper way of un/installing.

**Comment by jankammerath** [comment]
This application requires an X server and thus Docker is not even remotely possible.

**Comment by alexanderadam** [comment]
There might be a misconception here: Docker and an X server aren't excluding each other.
In the beginning of 2015 [Jessie Frazelle published a famous blog post where she explained how she runs things like Chrome or Spotify](https://blog.jessfraz.com/post/docker-containers-on-the-desktop/#5-chrome).
Since then many containers that required an X or Wayland server came out.
