### ISSUE TITLE
broken link

### ISSUE THREAD

**Issue by yahyanouali** [jankammerath/iptvx#86]
the link to installation instruction is broken, can you fix it please

**Comment by host755** [comment]
all links to instructions, wiki are broken and NO INSTRUCTIONS ara available anywhere... too bad

**Comment by jankammerath** [comment]
Have a look into the Makefile it is all in there. You even have Debian and RPM package build instructions. If you do not understand these, then it'll be impossible for you to get the application operational. This is also the reason why I shut down the website. There were too many people that wanted to install the application without knowing the fundamentals of Linux and POSIX systems.
